Build cow under OSX (with icon!)

diff --git a/cow/configure b/cow/configure
--- a/cow/configure
+++ b/cow/configure
@@ -1,5 +1,10 @@
 #!/bin/sh
 echo This script ignores all parameters.
 echo To change where cow will be installed, edit cow.pro!
-qmake-qt4
+if [ `uname` = "Darwin" ]; then
+  /usr/bin/qmake -spec macx-g++ || exit 1
+else
+  echo "ERROR: Can't find qmake-qt4 nor qmake in your path!"
+  exit 1
+fi
 echo Great! Now run \"make\" and \"make install\"!
