autoconf/automake tweaking for defile.conf

diff --git a/defile/configure b/defile/configure
--- a/defile/configure
+++ b/defile/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DATA_ETC_DIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot DATA_ETC_DIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP INSTALL_DEFILE_CONF_TRUE INSTALL_DEFILE_CONF_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3885,6 +3885,26 @@ fi
 done
 
 
+echo "$as_me:$LINENO: checking whether a defile.conf is already present" >&5
+echo $ECHO_N "checking whether a defile.conf is already present... $ECHO_C" >&6
+if test -f "$sysconfdir/defile.conf"; then
+  HAVE_DEFILE_CONF=yes;
+else
+  HAVE_DEFILE_CONF=no;
+fi
+echo "$as_me:$LINENO: result: $HAVE_DEFILE_CONF" >&5
+echo "${ECHO_T}$HAVE_DEFILE_CONF" >&6
+
+
+if test "$HAVE_DEFILE_CONF" = "no"; then
+  INSTALL_DEFILE_CONF_TRUE=
+  INSTALL_DEFILE_CONF_FALSE='#'
+else
+  INSTALL_DEFILE_CONF_TRUE='#'
+  INSTALL_DEFILE_CONF_FALSE=
+fi
+
+
                                         ac_config_files="$ac_config_files Makefile etc/Makefile defile.1 defile.conf"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -3988,6 +4008,13 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${INSTALL_DEFILE_CONF_TRUE}" && test -z "${INSTALL_DEFILE_CONF_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"INSTALL_DEFILE_CONF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"INSTALL_DEFILE_CONF\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4564,6 +4591,8 @@ s,@am__fastdepCC_TRUE@,$am__fastdepCC_TRUE,;t t
 s,@am__fastdepCC_FALSE@,$am__fastdepCC_FALSE,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@INSTALL_DEFILE_CONF_TRUE@,$INSTALL_DEFILE_CONF_TRUE,;t t
+s,@INSTALL_DEFILE_CONF_FALSE@,$INSTALL_DEFILE_CONF_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
