replacetables doesn't try to update database when parse fails now writing the 'internal' field for jacks to infiles

diff --git a/sedpy/replacetables b/sedpy/replacetables
--- a/sedpy/replacetables
+++ b/sedpy/replacetables
@@ -2,8 +2,14 @@
 
 [ -d out ] || mkdir out
 ./sedparser.py
-[ -d /data/sedweb ] || mkdir /data/sedweb
-[ -d /data/sedweb/out ] || mkdir /data/sedweb/out
-cp out/* /data/sedweb/out/
-echo "**Enter sql root password to update tables**"
-mysql -u root -p < replacetables.sql > sqlout.txt
+if [ "$?" -eq 0 ]
+then
+  [ -d /data/sedweb ] || mkdir /data/sedweb
+  [ -d /data/sedweb/out ] || mkdir /data/sedweb/out
+  cp out/* /data/sedweb/out/
+  echo "**Enter sql root password to update tables**"
+  mysql -u root -p < replacetables.sql > sqlout.txt
+else
+  echo "Parsing failed, not updating database"
+fi
+
